export default [
  { name: "Accounting", id: "0" },
  { name: "Actuarial Science", id: "1" },
  { name: "Advertising", id: "2" },
  { name: "Aerospace Engineering", id: "3" },
  { name: "African Languages, Literatures, and Linguistics", id: "4" },
  { name: "African Studies", id: "5" },
  { name: "African-American Studies", id: "6" },
  { name: "Agricultural Business and Management", id: "7" },
  { name: "Agricultural Economics", id: "8" },
  { name: "Agricultural Education", id: "9" },
  { name: "Agricultural Journalism", id: "10" },
  { name: "Agricultural Mechanization", id: "11" },
  { name: "Agricultural Technology Management", id: "12" },
  { name: "Agricultural/Biological Engineering and Bioengineering", id: "13" },
  { name: "Agriculture", id: "14" },
  { name: "Agronomy and Crop Science", id: "15" },
  { name: "Air Traffic Control", id: "16" },
  { name: "American History", id: "17" },
  { name: "American Literature", id: "18" },
  { name: "American Sign Language", id: "19" },
  { name: "American Studies", id: "20" },
  { name: "Anatomy", id: "21" },
  { name: "Ancient Studies", id: "22" },
  { name: "Animal Behavior and Ethology", id: "23" },
  { name: "Animal Science", id: "24" },
  { name: "Animation and Special Effects", id: "25" },
  { name: "Anthropology", id: "26" },
  { name: "Applied Mathematics", id: "27" },
  { name: "Aquaculture", id: "28" },
  { name: "Aquatic Biology", id: "29" },
  { name: "Arabic", id: "30" },
  { name: "Archeology", id: "31" },
  { name: "Architectural Engineering", id: "32" },
  { name: "Architectural History", id: "33" },
  { name: "Architecture", id: "34" },
  { name: "Art", id: "35" },
  { name: "Art Education", id: "36" },
  { name: "Art History", id: "37" },
  { name: "Art Therapy", id: "38" },
  { name: "Artificial Intelligence and Robotics", id: "39" },
  { name: "Asian-American Studies", id: "40" },
  { name: "Astronomy", id: "41" },
  { name: "Astrophysics", id: "42" },
  { name: "Athletic Training", id: "43" },
  { name: "Atmospheric Science", id: "44" },
  { name: "Automotive Engineering", id: "45" },
  { name: "Aviation", id: "46" },
  { name: "Bakery Science", id: "47" },
  { name: "Biblical Studies", id: "48" },
  { name: "Biochemistry", id: "49" },
  { name: "Bioethics", id: "50" },
  { name: "Biology", id: "51" },
  { name: "Biomedical Engineering", id: "52" },
  { name: "Biomedical Science", id: "53" },
  { name: "Biopsychology", id: "54" },
  { name: "Biotechnology", id: "55" },
  { name: "Botany/Plant Biology", id: "56" },
  { name: "Business Administration/Management", id: "57" },
  { name: "Business Communications", id: "58" },
  { name: "Business Education", id: "59" },
  { name: "Canadian Studies", id: "60" },
  { name: "Caribbean Studies", id: "61" },
  { name: "Cell Biology", id: "62" },
  { name: "Ceramic Engineering", id: "63" },
  { name: "Ceramics", id: "64" },
  { name: "Chemical Engineering", id: "65" },
  { name: "Chemical Physics", id: "66" },
  { name: "Chemistry", id: "67" },
  { name: "Child Care", id: "68" },
  { name: "Child Development", id: "69" },
  { name: "Chinese", id: "70" },
  { name: "Chiropractic", id: "71" },
  { name: "Church Music", id: "72" },
  { name: "Cinematography and Film/Video Production", id: "73" },
  { name: "Circulation Technology", id: "74" },
  { name: "Civil Engineering", id: "75" },
  { name: "Classics", id: "76" },
  { name: "Clinical Psychology", id: "77" },
  { name: "Cognitive Psychology", id: "78" },
  { name: "Communication Disorders", id: "79" },
  {
    name: "Communications Studies/Speech Communication and Rhetoric",
    id: "80",
  },
  { name: "Comparative Literature", id: "81" },
  { name: "Computer and Information Science", id: "82" },
  { name: "Computer Engineering", id: "83" },
  { name: "Computer Graphics", id: "84" },
  { name: "Computer Systems Analysis", id: "85" },
  { name: "Construction Management", id: "86" },
  { name: "Counseling", id: "87" },
  { name: "Crafts", id: "88" },
  { name: "Creative Writing", id: "89" },
  { name: "Criminal Science", id: "90" },
  { name: "Criminology", id: "91" },
  { name: "Culinary Arts", id: "92" },
  { name: "Dance", id: "93" },
  { name: "Data Processing", id: "94" },
  { name: "Dental Hygiene", id: "95" },
  { name: "Developmental Psychology", id: "96" },
  { name: "Diagnostic Medical Sonography", id: "97" },
  { name: "Dietetics", id: "98" },
  { name: "Digital Communications and Media/Multimedia", id: "99" },
  { name: "Drawing", id: "100" },
  { name: "Early Childhood Education", id: "101" },
  { name: "East Asian Studies", id: "102" },
  { name: "East European Studies", id: "103" },
  { name: "Ecology", id: "104" },
  { name: "Economics", id: "105" },
  { name: "Education", id: "106" },
  { name: "Education Administration", id: "107" },
  { name: "Education of the Deaf", id: "108" },
  { name: "Educational Psychology", id: "109" },
  { name: "Electrical Engineering", id: "110" },
  { name: "Elementary Education", id: "111" },
  { name: "Engineering Mechanics", id: "112" },
  { name: "Engineering Physics", id: "113" },
  { name: "English", id: "114" },
  { name: "English Composition", id: "115" },
  { name: "English Literature", id: "116" },
  { name: "Entomology", id: "117" },
  { name: "Entrepreneurship", id: "118" },
  { name: "Environmental Design/Architecture", id: "119" },
  { name: "Environmental Science", id: "120" },
  { name: "Environmental/Environmental Health Engineering", id: "121" },
  { name: "Epidemiology", id: "122" },
  { name: "Equine Studies", id: "123" },
  { name: "Ethnic Studies", id: "124" },
  { name: "European History", id: "125" },
  { name: "Experimental Pathology", id: "126" },
  { name: "Experimental Psychology", id: "127" },
  { name: "Fashion Design", id: "128" },
  { name: "Fashion Merchandising", id: "129" },
  { name: "Feed Science", id: "130" },
  { name: "Fiber, Textiles, and Weaving Arts", id: "131" },
  { name: "Film", id: "132" },
  { name: "Finance", id: "133" },
  { name: "Floriculture", id: "134" },
  { name: "Food Science", id: "135" },
  { name: "Forensic Science", id: "136" },
  { name: "Forestry", id: "137" },
  { name: "French", id: "138" },
  { name: "Furniture Design", id: "139" },
  { name: "Game Design", id: "140" },
  { name: "Gay and Lesbian Studies", id: "141" },
  { name: "Genetics", id: "142" },
  { name: "Geography", id: "143" },
  { name: "Geological Engineering", id: "144" },
  { name: "Geology", id: "145" },
  { name: "Geophysics", id: "146" },
  { name: "German", id: "147" },
  { name: "Gerontology", id: "148" },
  { name: "Government", id: "149" },
  { name: "Graphic Design", id: "150" },
  { name: "Health Administration", id: "151" },
  { name: "Hebrew", id: "152" },
  { name: "Hispanic-American, Puerto Rican, and Chicano Studies", id: "153" },
  { name: "Historic Preservation", id: "154" },
  { name: "History", id: "155" },
  { name: "Home Economics", id: "156" },
  { name: "Horticulture", id: "157" },
  { name: "Hospitality", id: "158" },
  { name: "Human Development", id: "159" },
  { name: "Human Resources Management", id: "160" },
  { name: "Illustration", id: "161" },
  { name: "Industrial Design", id: "162" },
  { name: "Industrial Engineering", id: "163" },
  { name: "Industrial Management", id: "164" },
  { name: "Industrial Psychology", id: "165" },
  { name: "Information Technology", id: "166" },
  { name: "Interior Architecture", id: "167" },
  { name: "Interior Design", id: "168" },
  { name: "International Agriculture", id: "169" },
  { name: "International Business", id: "170" },
  { name: "International Relations", id: "171" },
  { name: "International Studies", id: "172" },
  { name: "Islamic Studies", id: "173" },
  { name: "Italian", id: "174" },
  { name: "Japanese", id: "175" },
  { name: "Jazz Studies", id: "176" },
  { name: "Jewelry and Metalsmithing", id: "177" },
  { name: "Jewish Studies", id: "178" },
  { name: "Journalism", id: "179" },
  { name: "Kinesiology", id: "180" },
  { name: "Korean", id: "181" },
  { name: "Land Use Planning and Management", id: "182" },
  { name: "Landscape Architecture", id: "183" },
  { name: "Landscape Horticulture", id: "184" },
  { name: "Latin American Studies", id: "185" },
  { name: "Library Science", id: "186" },
  { name: "Linguistics", id: "187" },
  { name: "Logistics Management", id: "188" },
  { name: "Management Information Systems", id: "189" },
  { name: "Managerial Economics", id: "190" },
  { name: "Marine Biology", id: "191" },
  { name: "Marine Science", id: "192" },
  { name: "Marketing", id: "193" },
  { name: "Mass Communication", id: "194" },
  { name: "Massage Therapy", id: "195" },
  { name: "Materials Science", id: "196" },
  { name: "Mathematics", id: "197" },
  { name: "Mechanical Engineering", id: "198" },
  { name: "Medical Technology", id: "199" },
  { name: "Medieval and Renaissance Studies", id: "200" },
  { name: "Mental Health Services", id: "201" },
  { name: "Merchandising and Buying Operations", id: "202" },
  { name: "Metallurgical Engineering", id: "203" },
  { name: "Microbiology", id: "204" },
  { name: "Middle Eastern Studies", id: "205" },
  { name: "Military Science", id: "206" },
  { name: "Mineral Engineering", id: "207" },
  { name: "Missions", id: "208" },
  { name: "Modern Greek", id: "209" },
  { name: "Molecular Biology", id: "210" },
  { name: "Molecular Genetics", id: "211" },
  { name: "Mortuary Science", id: "212" },
  { name: "Museum Studies", id: "213" },
  { name: "Music", id: "214" },
  { name: "Music Education", id: "215" },
  { name: "Music History", id: "216" },
  { name: "Music Management", id: "217" },
  { name: "Music Therapy", id: "218" },
  { name: "Musical Theater", id: "219" },
  { name: "Native American Studies", id: "220" },
  { name: "Natural Resources Conservation", id: "221" },
  { name: "Naval Architecture", id: "222" },
  { name: "Neurobiology", id: "223" },
  { name: "Neuroscience", id: "224" },
  { name: "Nuclear Engineering", id: "225" },
  { name: "Nursing", id: "226" },
  { name: "Nutrition", id: "227" },
  { name: "Occupational Therapy", id: "228" },
  { name: "Ocean Engineering", id: "229" },
  { name: "Oceanography", id: "230" },
  { name: "Operations Management", id: "231" },
  { name: "Organizational Behavior Studies", id: "232" },
  { name: "Painting", id: "233" },
  { name: "Paleontology", id: "234" },
  { name: "Pastoral Studies", id: "235" },
  { name: "Peace Studies", id: "236" },
  { name: "Petroleum Engineering", id: "237" },
  { name: "Pharmacology", id: "238" },
  { name: "Pharmacy", id: "239" },
  { name: "Philosophy", id: "240" },
  { name: "Photography", id: "241" },
  { name: "Photojournalism", id: "242" },
  { name: "Physical Education", id: "243" },
  { name: "Physical Therapy", id: "244" },
  { name: "Physician Assistant", id: "245" },
  { name: "Physics", id: "246" },
  { name: "Physiological Psychology", id: "247" },
  { name: "Piano", id: "248" },
  { name: "Planetary Science", id: "249" },
  { name: "Plant Pathology", id: "250" },
  { name: "Playwriting and Screenwriting", id: "251" },
  { name: "Political Communication", id: "252" },
  { name: "Political Science", id: "253" },
  { name: "Portuguese", id: "254" },
  { name: "Pre-Dentistry", id: "255" },
  { name: "Pre-Law", id: "256" },
  { name: "Pre-Medicine", id: "257" },
  { name: "Pre-Optometry", id: "258" },
  { name: "Pre-Seminary", id: "259" },
  { name: "Pre-Veterinary Medicine", id: "260" },
  { name: "Printmaking", id: "261" },
  { name: "Psychology", id: "262" },
  { name: "Public Administration", id: "263" },
  { name: "Public Health", id: "264" },
  { name: "Public Policy Analysis", id: "265" },
  { name: "Public Relations", id: "266" },
  { name: "Radio and Television", id: "267" },
  { name: "Radiologic Technology", id: "268" },
  { name: "Range Science and Management", id: "269" },
  { name: "Real Estate", id: "270" },
  { name: "Recording Arts Technology", id: "271" },
  { name: "Recreation Management", id: "272" },
  { name: "Rehabilitation Services", id: "273" },
  { name: "Religious Studies", id: "274" },
  { name: "Respiratory Therapy", id: "275" },
  { name: "Risk Management", id: "276" },
  { name: "Rural Sociology", id: "277" },
  { name: "Russian", id: "278" },
  { name: "Scandinavian Studies", id: "279" },
  { name: "Sculpture", id: "280" },
  { name: "Slavic Languages and Literatures", id: "281" },
  { name: "Social Psychology", id: "282" },
  { name: "Social Work", id: "283" },
  { name: "Sociology", id: "284" },
  { name: "Soil Science", id: "285" },
  { name: "Sound Engineering", id: "286" },
  { name: "South Asian Studies", id: "287" },
  { name: "Southeast Asia Studies", id: "288" },
  { name: "Spanish", id: "289" },
  { name: "Special Education", id: "290" },
  { name: "Speech Pathology", id: "291" },
  { name: "Sport and Leisure Studies", id: "292" },
  { name: "Sports Management", id: "293" },
  { name: "Statistics", id: "294" },
  { name: "Surveying", id: "295" },
  { name: "Sustainable Resource Management", id: "296" },
  { name: "Teacher Education", id: "297" },
  { name: "Teaching English as a Second Language", id: "298" },
  { name: "Technical Writing", id: "299" },
  { name: "Technology Education", id: "300" },
  { name: "Textile Engineering", id: "301" },
  { name: "Theatre", id: "302" },
  { name: "Theology", id: "303" },
  { name: "Tourism", id: "304" },
  { name: "Toxicology", id: "305" },
  { name: "Turfgrass Science", id: "306" },
  { name: "Urban Planning", id: "307" },
  { name: "Urban Studies", id: "308" },
  { name: "Visual Communication", id: "309" },
  { name: "Voice", id: "310" },
  { name: "Web Design", id: "311" },
  { name: "Webmaster and Web Management", id: "312" },
  { name: "Welding Engineering", id: "313" },
  { name: "Wildlife Management", id: "314" },
  { name: "Women's Studies", id: "315" },
  { name: "Youth Ministries", id: "316" },
  { name: "Zoology", id: "317" },
];
